import chalk from 'chalk';
import { PageHelper } from '../BaseHelper/page.helper';
import { expect } from '@playwright/test';

const mainMenuArray = [
    'Dashboard',
    'Expenses',
    'Advances',
    'Parties',
    'HR',
    'Work Flows',
    'Transactions',
    'Configurations',
    'Reports',
    'Switch Mode',
    'Settings',
    'Logout',
];

const menus = [
    {
        enableRecordWatcher: true,
        id: 1,
        uuid: '2f1bb7cf-af1d-4810-823a-c8156250e1b5',
        product_id: 4,
        name: 'Dashboard',
        label: 'Dashboard',
        display_name: 'Dashboard',
        image: 'grid_view',
        description: 'Finops Dashboard Module',
        root_path: '/',
        path: '/',
        ui_action_id: null,
        spacer_above: false,
        display_order: 1,
        active: true,
        attributes: null,
        ui_action: null,
        menus: [
            {
                enableRecordWatcher: true,
                id: 71,
                uuid: '58a0d551-eacc-4d72-9e71-7980d52c98a8',
                name: 'My Dashboard',
                label: 'Finops Dashboard',
                display_name: 'AP Dashboard',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 1,
            },
            {
                enableRecordWatcher: true,
                id: 92,
                uuid: '58a0d551-eacc-4d72-9e71-7980d52c98a8',
                name: 'Payment Dashboard',
                label: 'Finops Payment Dashboard',
                display_name: 'Payment Dashboard',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/payment_dashboard',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 10,
            },
            {
                enableRecordWatcher: true,
                id: 93,
                uuid: '58a0d551-eacc-4d72-9e71-7980d52c98a8',
                name: 'Approval Dashboard',
                label: 'Finops Approval Dashboard',
                display_name: 'Approval Dashboard',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/approval_dashboard',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: 20,
            },
            {
                enableRecordWatcher: true,
                id: 141,
                uuid: '58a0d551-eacc-4d72-9e71-7980d52c98a8',
                name: 'Notifications',
                label: 'Common Notifications',
                display_name: 'Notifications',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/notifications',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: 1000,
            },
            {
                enableRecordWatcher: true,
                id: 142,
                uuid: '58a0d551-eacc-4d72-9e71-7980d52c98a8',
                name: 'Search',
                label: 'Common Search',
                display_name: 'Search',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/search',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: 1000,
            },
        ],
    },
    {
        enableRecordWatcher: true,
        id: 14,
        uuid: '6c096f9c-c81c-45b6-8631-7122b62a0bc6',
        product_id: 4,
        name: 'Expenses',
        label: 'Expenses',
        display_name: 'Expenses',
        image: 'DocumentFileSidebarSvgIcon',
        description: 'Finops Expenses Module',
        root_path: '/expense',
        path: '/expenses',
        ui_action_id: null,
        spacer_above: false,
        display_order: 5,
        active: true,
        attributes: null,
        ui_action: null,
        menus: [
            {
                enableRecordWatcher: true,
                id: 51,
                uuid: 'f62f901e-8cdf-481a-bbc4-b3c2d8a18940',
                name: 'Expense Listing',
                label: 'Expenses',
                display_name: 'Expenses',
                image: null,
                description: 'Finops Expenses',
                ui_action_id: null,
                root_path: '/expense',
                path: '/expenses',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: 1,
            },
            {
                enableRecordWatcher: true,
                id: 32,
                uuid: 'c67ab9e8-4395-42a0-b8af-d83bfe98a598',
                name: 'EF Expense Detail',
                label: 'Expense Detail',
                display_name: 'Expense Detail',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: '',
                path: '/expense/d/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 52,
                uuid: '8f959f8b-3b47-4528-9d64-4c28ff46fd81',
                name: 'Expense creation',
                label: 'Expense creation',
                display_name: 'Expense creation',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/expense/c',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 73,
                uuid: 'c67ab9e8-4395-42a0-b8af-d83bfe98a598',
                name: 'EF Expense Edit',
                label: 'Expense Edit',
                display_name: 'Expense Edit',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/expense/[id]',
                visibility: false,
                attributes: null,
            },
        ],
    },
    {
        enableRecordWatcher: true,
        id: 10,
        uuid: '2b41d8ed-5462-4402-b946-0e07b2d62bdc',
        product_id: 4,
        name: 'Settings',
        label: 'Settings',
        display_name: 'Settings',
        image: 'MenuSettingSvgIcon',
        description: 'Finops portal setting',
        root_path: '/settings/my-profile',
        path: '/settings/my-profile',
        ui_action_id: null,
        spacer_above: false,
        display_order: 8,
        active: true,
        attributes: '',
        ui_action: null,
        menus: [
            {
                enableRecordWatcher: true,
                id: 68,
                uuid: 'c8af8a5f-8b5e-4e10-a31d-858dbe92c8e1',
                name: 'My Profile',
                label: 'Finops My Profile ',
                display_name: 'My Profile',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/settings/my-profile',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 1,
            },
            {
                enableRecordWatcher: true,
                id: 24,
                uuid: 'c3a4c02f-d31a-477b-921b-43b7403841b9',
                name: 'User Management',
                label: 'Finops User manangement',
                display_name: 'User Management',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/settings/user-management',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 2,
            },
            {
                enableRecordWatcher: true,
                id: 129,
                uuid: 'c8af8a5f-8b5e-4e10-a31d-858dbe92c8e1',
                name: 'Settings Menu',
                label: 'Settings Menu',
                display_name: 'Settings Menu',
                image: null,
                description: 'Settings Menu for pwa',
                ui_action_id: null,
                root_path: null,
                path: '/settings',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: 3,
            },
        ],
    },
    {
        enableRecordWatcher: true,
        id: 15,
        uuid: '0df03edc-ba3b-4520-8ebf-0dceee23a33b',
        product_id: 4,
        name: 'Advances',
        label: 'Advances',
        display_name: 'Advances',
        image: 'EmployeeAdvanceSvgIcon',
        description: 'Employee Advances',
        root_path: null,
        path: '/employee-advances',
        ui_action_id: null,
        spacer_above: false,
        display_order: 10,
        active: true,
        attributes: {},
        ui_action: null,
        menus: [
            {
                enableRecordWatcher: true,
                id: 30,
                uuid: 'e9805ecb-5f25-4704-af9e-f3e4caf2b4e1',
                name: 'Employee Advance listing',
                label: 'Employee Advance',
                display_name: 'Employee Advance',
                image: 'EmployeeAdvanceSvgIcon',
                description: 'employee advance',
                ui_action_id: null,
                root_path: null,
                path: '/employee-advances',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: 1,
            },
            {
                enableRecordWatcher: true,
                id: 33,
                uuid: 'ee5c3804-c69f-4faa-b533-594a4a4256fc',
                name: ' Employee Advance Detail ',
                label: 'Employee Advance Detail ',
                display_name: 'Employee Advance Detail ',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/employee-advance/d/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 175,
                uuid: 'ee5c3804-c69f-4faa-b533-594a4a4256fc',
                name: ' Employee Advance Creation ',
                label: 'Employee Advance Creation ',
                display_name: 'Employee Advance Creation ',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/employee-advance/c',
                visibility: false,
                attributes: null,
            },
        ],
    },
    {
        enableRecordWatcher: true,
        id: 3,
        uuid: '0e8bf89c-c297-4352-a329-88531fee1d07',
        product_id: 4,
        name: 'Parties',
        label: 'Parties',
        display_name: 'Parties',
        image: 'SidebarVendorSvgIcon',
        description: 'finops portal parties ',
        root_path: '/vendor',
        path: '/vendor',
        ui_action_id: null,
        spacer_above: true,
        display_order: 20,
        active: true,
        attributes: null,
        ui_action: null,
        menus: [
            {
                enableRecordWatcher: true,
                id: 2,
                uuid: 'f5518463-0728-4af4-83ed-dd8198b06816',
                name: 'My Businesses listing',
                label: 'Finops My Businesses',
                display_name: 'My Businesses',
                image: null,
                description: 'finops my businesses',
                ui_action_id: null,
                root_path: null,
                path: '/my-businesses',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 1,
            },
            {
                enableRecordWatcher: true,
                id: 31,
                uuid: '3c15a0e8-da52-4c18-b133-6e541423e01a',
                name: 'EF MY Business Detail',
                label: 'EF MY Business Detail',
                display_name: 'MY Business Detail',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/my-business/d/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 3,
                uuid: 'a0c73b22-b6e4-458b-a9c6-c7c14be9d74c',
                name: 'My Vendors listing',
                label: 'Finops My Vendors',
                display_name: 'My Vendors',
                image: null,
                description: 'finops my vendors',
                ui_action_id: null,
                root_path: null,
                path: '/vendors',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 2,
            },
            {
                enableRecordWatcher: true,
                id: 48,
                uuid: 'a0c73b22-b6e4-458b-a9c6-c7c14be9d74c',
                name: 'My Vendors Details',
                label: 'Finops My Vendors Detail',
                display_name: 'My Vendors Details',
                image: null,
                description: 'finops my vendors',
                ui_action_id: null,
                root_path: null,
                path: '/vendor/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 4,
                uuid: '61636e15-6314-4e12-a189-0b0d37622792',
                name: 'Vendor Invitations listing',
                label: 'Vendor Invitations',
                display_name: 'Vendor Invitations',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/vendor-invitations',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 3,
            },
            {
                enableRecordWatcher: true,
                id: 36,
                uuid: '61636e15-6314-4e12-a189-0b0d37622792',
                name: 'Vendor Invitations Detail',
                label: 'Vendor Invitations Detail',
                display_name: 'Vendor Invitations Detail',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/vendor-invitation/[id]',
                visibility: false,
                attributes: null,
            },
        ],
    },
    {
        enableRecordWatcher: true,
        id: 5,
        uuid: '966201ed-b148-42bc-b71e-bdfbbebd2864',
        product_id: 4,
        name: 'HR',
        label: 'HR',
        display_name: 'HR',
        image: 'SidebarHrSvgIcon',
        description: 'hr menu',
        root_path: '/hr',
        path: '/hr',
        ui_action_id: null,
        spacer_above: false,
        display_order: 25,
        active: true,
        attributes: null,
        ui_action: null,
        menus: [
            {
                enableRecordWatcher: true,
                id: 5,
                uuid: 'b289f4e6-5a54-4c75-aca6-556e74212fb2',
                name: 'Employee Listing',
                label: 'HR employees',
                display_name: 'Employees',
                image: null,
                description: 'HR employees',
                ui_action_id: null,
                root_path: null,
                path: '/employees',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 1,
            },
            {
                enableRecordWatcher: true,
                id: 37,
                uuid: 'b9b7fa07-796b-4665-b46e-14351422cfe1',
                name: 'Employee Detail',
                label: 'Employee Detail',
                display_name: 'Employee Detail',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/employee/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 6,
                uuid: '872441c4-1908-453b-a17b-de6a10eed08f',
                name: 'Departments listing',
                label: 'HR departments',
                display_name: 'Departments',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/departments',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 2,
            },
            {
                enableRecordWatcher: true,
                id: 38,
                uuid: 'b0088f96-4d18-43a1-b5a0-425065c71987',
                name: 'Department Detail',
                label: 'Department Detail',
                display_name: 'Department Detail',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/department/d/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 7,
                uuid: '0d3a6541-c603-464e-98f5-4cc208cc9093',
                name: 'Designations Listing',
                label: 'HR designations',
                display_name: 'Designations',
                image: null,
                description: 'HR designations',
                ui_action_id: null,
                root_path: null,
                path: '/designations',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 3,
            },
            {
                enableRecordWatcher: true,
                id: 39,
                uuid: '0d3a6541-c603-464e-98f5-4cc208cc9093',
                name: 'Designations Detail',
                label: 'Designations Detail',
                display_name: 'Designations Detail',
                image: null,
                description: 'HR designations',
                ui_action_id: null,
                root_path: null,
                path: '/designation/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 44,
                uuid: '88a93e7d-25ee-4098-bd4b-1769912850bf',
                name: 'Grades Listing',
                label: 'Employee Grades',
                display_name: 'Grades',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/grades',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 10,
            },
        ],
    },
    {
        enableRecordWatcher: true,
        id: 6,
        uuid: '262b7a89-9cdd-4d06-a2c0-398cd6badc92',
        product_id: 4,
        name: 'Work Flows',
        label: 'Work Flows',
        display_name: 'Work Flows',
        image: 'WorkFlowSvgIcon',
        description: null,
        root_path: '/work-flow',
        path: '/work-flows',
        ui_action_id: null,
        spacer_above: true,
        display_order: 35,
        active: true,
        attributes: null,
        ui_action: null,
        menus: [
            {
                enableRecordWatcher: true,
                id: 8,
                uuid: 'a21992bc-b8dd-4e14-a0e8-7ac5b17438ce',
                name: 'Expense Approvals Listing',
                label: 'Workflow Expense approvals',
                display_name: 'Expense  Approvals',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: '/expense-approval',
                path: '/expense-approval',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 1,
            },
            {
                enableRecordWatcher: true,
                id: 57,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Finops Approval Detail',
                label: 'Finops Approval Detail',
                display_name: 'Finops Approval Detail',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/expense-approval/finops/d/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 56,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Payment Approval Detail',
                label: 'Payment Approval Detail',
                display_name: 'Payment Approval Detail',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/expense-approval/payment/d/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 81,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Verification Approval Edit ',
                label: 'Verification Approval Edit ',
                display_name: 'Verification Approval Edit ',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/expense-approval/verification/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 60,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Finops Approval Create ',
                label: 'Finops Approval Create ',
                display_name: 'Finops Approval Create ',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/expense-approval/finops/c',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 59,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Payment Approval Create ',
                label: 'Payment Approval Create ',
                display_name: 'Payment Approval Create ',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/expense-approval/payment/c',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 79,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Finops Approval  Edit',
                label: 'Finops Approval  Edit',
                display_name: 'Finops Approval  Edit',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/expense-approval/finops/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 58,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Verification Approval Create ',
                label: 'Verification Approval Create ',
                display_name: 'Verification Approval Create ',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/expense-approval/verification/c',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 69,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Verification Approval Detail ',
                label: 'Verification Approval Detail ',
                display_name: 'Verification Approval Detail ',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/expense-approval/verification/d/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 83,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Payment Approval Edit',
                label: 'Payment Approval Edit',
                display_name: 'Payment Approval Edit',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/expense-approval/payment/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 50,
                uuid: 'ba7fba7a-27b3-401c-b27c-344248ac6ae8',
                name: 'Advance Approvals Listing',
                label: 'Advance Approvals',
                display_name: 'Advance Approvals',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/advance-approval',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 2,
            },
            {
                enableRecordWatcher: true,
                id: 61,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Verification Advance Approval Create ',
                label: 'Verification Advance Approval Create ',
                display_name: 'Verification Advance Approval Create ',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/advance-approval/verification/c',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 62,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Finops Advance Approval Create ',
                label: 'Finops Advance Approval Create ',
                display_name: 'Finops Advance Approval Create ',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/advance-approval/finops/c',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 63,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Payment Advance Approval Create ',
                label: 'Payment Advance Approval Create ',
                display_name: 'Payment Advance Approval Create ',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/advance-approval/payment/c',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 64,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Payment Advance Approval Detail ',
                label: 'Payment Advance Approval Detail ',
                display_name: 'Payment Advance Approval Detail ',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/advance-approval/payment/d/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 65,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Finops Advance Approval Detail ',
                label: 'Finops Advance Approval Detail ',
                display_name: 'Finops Advance Approval Detail ',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/advance-approval/finops/d/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 66,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Verification Advance Approval Detail ',
                label: 'Verification Advance Approval Detail ',
                display_name: 'Verification Advance Approval Detail ',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/advance-approval/verification/d/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 84,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Verification Advance Approval Edit ',
                label: 'Verification Advance Approval Edit ',
                display_name: 'Verification Advance Approval Edit ',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/advance-approval/verification/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 85,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Finops Advance Approval Edit',
                label: 'Finops Advance Approval Edit',
                display_name: 'Finops Advance Approval Edit',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/advance-approval/finops/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 86,
                uuid: 'f6ad29b1-74b1-4736-b3ca-5b97c9e11c44',
                name: 'Payment Advance Approval Edit ',
                label: 'Payment Advance Approval Edit ',
                display_name: 'Payment Advance Approval Edit ',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/advance-approval/payment/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 10,
                uuid: 'bd5ce8c1-339f-450a-b43d-0fd0c6491fcc',
                name: 'Verification Limits Listings',
                label: 'Workflows Verification Limits',
                display_name: 'Verification Limits',
                image: null,
                description: 'Workflows Verification Limits',
                ui_action_id: null,
                root_path: null,
                path: '/verification-limit',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: 3,
            },
            {
                enableRecordWatcher: true,
                id: 11,
                uuid: 'd96974ab-f7b5-43c5-8069-8a30e562f740',
                name: 'Payment Limits',
                label: 'Workflows Payment Limits',
                display_name: 'Payment Limits',
                image: null,
                description: 'Workflows Payment Limits',
                ui_action_id: null,
                root_path: null,
                path: '/payment-limit',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: 4,
            },
            {
                enableRecordWatcher: true,
                id: 12,
                uuid: 'dc89017c-0dc1-4120-930a-24ddbfb22dff',
                name: 'Finops Limits',
                label: 'Workflows Finops Limits',
                display_name: 'Finops Limits',
                image: null,
                description: 'Workflows Finops Limits',
                ui_action_id: null,
                root_path: null,
                path: '/finops_limits',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: 5,
            },
            {
                enableRecordWatcher: true,
                id: 140,
                uuid: 'd9c17370-e28a-4e96-bf75-7d2780b8943d',
                name: 'Approval Delegations',
                label: 'Approval Delegations',
                display_name: 'Approval Delegations',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/approval-delegations',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 10,
            },
            {
                enableRecordWatcher: true,
                id: 138,
                uuid: '09867d83-22d7-4a1d-9235-9bd9a3ec0277',
                name: 'Expense Approval Limits',
                label: 'Expense Approval Limits',
                display_name: 'Expense Approval Limits',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/expense-approval-limits',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 20,
            },
            {
                enableRecordWatcher: true,
                id: 139,
                uuid: '09867d83-22d7-4a1d-9235-9bd9a3ec0277',
                name: 'Advance Approval Limits',
                label: 'Advance Approval Limits',
                display_name: 'Advance Approval Limits',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/advance-approval-limits',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 30,
            },
        ],
    },
    {
        enableRecordWatcher: true,
        id: 8,
        uuid: '61d59939-beeb-4493-b1fc-6d830815d26a',
        product_id: 4,
        name: 'Transactions',
        label: 'Payment',
        display_name: 'Transactions',
        image: 'DashboardPaymentSvgIcon',
        description: null,
        root_path: '/payment',
        path: '/payments',
        ui_action_id: null,
        spacer_above: false,
        display_order: 40,
        active: true,
        attributes: null,
        ui_action: null,
        menus: [
            {
                enableRecordWatcher: true,
                id: 19,
                uuid: '4ee4f4d2-42eb-4e1c-90ca-9d2b7dbb00c4',
                name: 'All Payments',
                label: 'Payments All Payments',
                display_name: 'All Payments',
                image: null,
                description: 'Payments All Payments',
                ui_action_id: null,
                root_path: null,
                path: '/all-payments',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 2,
            },
            {
                enableRecordWatcher: true,
                id: 144,
                uuid: '8c31c497-d9c8-4bcc-852b-ab140ddd9376',
                name: 'Cash Transfers',
                label: 'Cash Transfers',
                display_name: 'Cash Transactions',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/cash-transfers',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 3,
            },
            {
                enableRecordWatcher: true,
                id: 20,
                uuid: '5b0a982e-9175-4eb1-bccd-ac2494404f3b',
                name: 'Online Bank Transfers',
                label: 'Payments Online Bank Transfers',
                display_name: 'Online Bank Transfers',
                image: null,
                description: 'Payments Online Bank Transfers',
                ui_action_id: null,
                root_path: null,
                path: '/bank-transfers',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 5,
            },
            {
                enableRecordWatcher: true,
                id: 77,
                uuid: 'f2f1b5cf-d4ba-472c-a8e6-09fdce43c6b4',
                name: 'Payment Detail Page',
                label: 'Payment Detail Page',
                display_name: 'Payment Detail Page',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/payment/d/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 176,
                uuid: '5b0a982e-9175-4eb1-bccd-ac2494404f3b',
                name: 'Offline Bank Transfers',
                label: 'Payments Offline Bank Transfers',
                display_name: 'Offline Bank Transfers',
                image: null,
                description: 'Payments Offline Bank Transfers',
                ui_action_id: null,
                root_path: null,
                path: '/offline-bank-transfers',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 6,
            },
            {
                enableRecordWatcher: true,
                id: 21,
                uuid: 'a5d38721-6af0-44ca-851d-b08dd0924dc6',
                name: 'Cheque Payments Listing',
                label: 'Payments Cheque Payments',
                display_name: 'Cheque Payments',
                image: null,
                description: 'Payments Cheque Payments',
                ui_action_id: null,
                root_path: null,
                path: '/cheque-payments',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 8,
            },
            {
                enableRecordWatcher: true,
                id: 77,
                uuid: 'f2f1b5cf-d4ba-472c-a8e6-09fdce43c6b4',
                name: 'Payment Detail Page',
                label: 'Payment Detail Page',
                display_name: 'Payment Detail Page',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/payment/d/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 132,
                uuid: 'f2841c20-60ee-4c8c-aec9-cad9f98f51ba',
                name: 'Bank Accounts',
                label: 'Finops Bank Accounts',
                display_name: 'Bank Accounts',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/bank-accounts',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 10,
            },
            {
                enableRecordWatcher: true,
                id: 136,
                uuid: 'eb41e395-d9e3-4ce5-85c2-246f5d8b61d6',
                name: 'Gstr2b Items',
                label: 'Gstr2b Items',
                display_name: 'Gstr2b ',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: '/gstr2b-item',
                path: '/gstr2b-items',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 30,
            },
            {
                enableRecordWatcher: true,
                id: 137,
                uuid: 'eb41e395-d9e3-4ce5-85c2-246f5d8b61d6',
                name: 'Gstr2b Detail Item',
                label: 'Gstr2b Detail Item',
                display_name: 'Gstr2b Detail Item',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/gstr2b-item/d/[id]',
                visibility: false,
                attributes: null,
            },
        ],
    },
    {
        enableRecordWatcher: true,
        id: 50,
        uuid: '8df24048-8c6d-4e64-acec-da7f0993b26b',
        product_id: 4,
        name: 'Configurations',
        label: 'Configurations',
        display_name: 'Configurations',
        image: 'SidebaconfigurationsSvgIcon',
        description: 'configuartions',
        root_path: '/configuration',
        path: '/configurations',
        ui_action_id: null,
        spacer_above: false,
        display_order: 41,
        active: true,
        attributes: {
            no_pwa: true,
        },
        ui_action: null,
        menus: [
            {
                enableRecordWatcher: true,
                id: 180,
                uuid: 'b289f4e6-5a54-4c75-aca6-556e74212fb2',
                name: 'Configurations',
                label: 'Configurations',
                display_name: 'Configurations',
                image: null,
                description: 'Configurations List',
                ui_action_id: null,
                root_path: null,
                path: '/configurations',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: null,
            },
        ],
    },
    {
        enableRecordWatcher: true,
        id: 7,
        uuid: '8df24048-8c6d-4e64-acec-da7f0993b26b',
        product_id: 4,
        name: 'Configurations',
        label: 'Configurations',
        display_name: 'Configurations',
        image: 'SidebaconfigurationsSvgIcon',
        description: 'configuartions',
        root_path: '/configuration',
        path: '/configurations',
        ui_action_id: null,
        spacer_above: false,
        display_order: 41,
        active: true,
        attributes: {
            no_pwa: true,
            hide_submenu: true,
        },
        ui_action: null,
        menus: [
            {
                enableRecordWatcher: true,
                id: 180,
                uuid: 'b289f4e6-5a54-4c75-aca6-556e74212fb2',
                name: 'Configurations',
                label: 'Configurations',
                display_name: 'Configurations',
                image: null,
                description: 'Configurations List',
                ui_action_id: null,
                root_path: null,
                path: '/configurations',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: 1,
            },
            {
                enableRecordWatcher: true,
                id: 13,
                uuid: 'ad328abe-d840-442d-a680-249f1ab246d5',
                name: 'User Groups Listings',
                label: 'Configurations User Groups',
                display_name: 'User Groups',
                image: null,
                description:
                    'Organising and managing users based on specific criteria or roles.',
                ui_action_id: null,
                root_path: null,
                path: '/user-groups',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 1,
            },
            {
                enableRecordWatcher: true,
                id: 49,
                uuid: 'ad328abe-d840-442d-a680-249f1ab246d5',
                name: 'User Groups Details',
                label: 'User Groups Details',
                display_name: 'User Groups Details',
                image: null,
                description: 'Configurations User Groups',
                ui_action_id: null,
                root_path: null,
                path: '/user-group/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 178,
                uuid: 'b289f4e6-5a54-4c75-aca6-556e74212fb2',
                name: 'Email Messages',
                label: 'Email Messages',
                display_name: 'Email Messages',
                image: null,
                description: 'Review all messages and emails ',
                ui_action_id: null,
                root_path: null,
                path: '/email_messages',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 2,
            },
            {
                enableRecordWatcher: true,
                id: 14,
                uuid: 'b9212ab1-e578-4a1b-a7d2-f5856478445e',
                name: 'Expense Heads Listing',
                label: 'Configurations Expense Heads',
                display_name: 'Expense Heads',
                image: null,
                description: 'Create and manage all Expense heads',
                ui_action_id: null,
                root_path: null,
                path: '/expense-heads',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 2,
            },
            {
                enableRecordWatcher: true,
                id: 42,
                uuid: 'ba8f3891-6a7d-46b6-ae6c-e8e6eaba93b0',
                name: 'Expense Head Detail',
                label: 'Expense Head Detail',
                display_name: 'Expense Head Detail',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/expense-head/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 15,
                uuid: '5d3a2d67-bcd5-4bd9-af7c-89d95ff0f1c8',
                name: 'Choice Types Listing',
                label: 'Configurations Choice Types',
                display_name: 'Choice Types',
                image: null,
                description:
                    'Define specific options or categories that can be selected within Different modules',
                ui_action_id: null,
                root_path: null,
                path: '/choice-types',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 3,
            },
            {
                enableRecordWatcher: true,
                id: 43,
                uuid: '5d3a2d67-bcd5-4bd9-af7c-89d95ff0f1c8',
                name: 'Choice Types Detail',
                label: 'Choice Types Detail',
                display_name: 'Choice Types Detail',
                image: null,
                description: 'Configurations Choice Types',
                ui_action_id: null,
                root_path: null,
                path: '/choice-type/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 179,
                uuid: 'b289f4e6-5a54-4c75-aca6-556e74212fb2',
                name: 'Email Accounts',
                label: 'Email Accounts',
                display_name: 'Email Accounts',
                image: null,
                description: 'Create and manage email accounts',
                ui_action_id: null,
                root_path: null,
                path: '/email_accounts',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 4,
            },
            {
                enableRecordWatcher: true,
                id: 16,
                uuid: 'cbb8f5af-f203-4388-b4da-c81a1aa9f1d5',
                name: 'Custom Fields',
                label: 'Configurations Custom Fields',
                display_name: 'Custom Fields',
                image: null,
                description:
                    'Add additional data fields to different categories',
                ui_action_id: null,
                root_path: null,
                path: '/custom-fields',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 4,
            },
            {
                enableRecordWatcher: true,
                id: 17,
                uuid: 'cba90a38-b24e-41ed-9ff7-c9051d249d37',
                name: 'Document Preferences Listings',
                label: 'Configurations Document Preferences',
                display_name: 'Document Preferences',
                image: null,
                description:
                    'Manage the mandatory documents that need to be submitted by Invited vendors',
                ui_action_id: null,
                root_path: null,
                path: '/document-preferences',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 5,
            },
            {
                enableRecordWatcher: true,
                id: 18,
                uuid: '49af8ec0-ed9a-48f8-9d6c-cd999bd6316e',
                name: 'Payment Modes Listing',
                label: 'Payment Payment Modes',
                display_name: 'Payment Modes',
                image: null,
                description:
                    'Manage and Set up various payment methods that can be used for your business transactions',
                ui_action_id: null,
                root_path: null,
                path: '/payment-modes',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 6,
            },
            {
                enableRecordWatcher: true,
                id: 177,
                uuid: '44a71a7a-d642-4d5b-8279-01fcb8b44b9f',
                name: 'Payout/Recon',
                label: 'Payout/Recon',
                display_name: 'Payout/Recon',
                image: null,
                description: 'Generate a new Payout or Create a new Recon',
                ui_action_id: null,
                root_path: null,
                path: '/payout-recon',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 7,
            },
            {
                enableRecordWatcher: true,
                id: 9,
                uuid: '5dbb6dcd-29bb-4844-9900-5dae51ee4e8b',
                name: 'Limits Config Listing',
                label: 'Workflows Limits Config',
                display_name: 'Limits Config',
                image: null,
                description: 'Configure limits of Workflows ',
                ui_action_id: null,
                root_path: null,
                path: '/limit-config',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 8,
            },
            {
                enableRecordWatcher: true,
                id: 75,
                uuid: '4485a3a1-6437-49a6-b8cb-4f3bba1c3b91',
                name: 'User Roles',
                label: 'User Roles',
                display_name: 'User Roles',
                image: null,
                description: 'View the roles assigned to users',
                ui_action_id: null,
                root_path: null,
                path: '/roles',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 100,
            },
            {
                enableRecordWatcher: true,
                id: 97,
                uuid: '4d8fb075-46fc-41c6-a6e0-b1141706de90',
                name: 'Advance Categories',
                label: 'Advance Categories',
                display_name: 'Advance Categories',
                image: null,
                description: 'Create categories to raise Advances',
                ui_action_id: null,
                root_path: null,
                path: '/advance-categories',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 120,
            },
            {
                enableRecordWatcher: true,
                id: 98,
                uuid: '4d8fb075-46fc-41c6-a6e0-b1141706de90',
                name: 'Advance Category Detail',
                label: 'Advance Category Detail',
                display_name: 'Advance Category Detail',
                image: null,
                description: null,
                ui_action_id: null,
                root_path: null,
                path: '/advance-category/d/[id]',
                visibility: false,
                attributes: null,
            },
            {
                enableRecordWatcher: true,
                id: 143,
                uuid: '5dbb6dcd-29bb-4844-9900-5dae51ee4e8b',
                name: 'Bulk Upload Listing',
                label: 'Bulk Uploads',
                display_name: 'Bulk Uploads',
                image: null,
                description: 'Upload and Process large volumes of data',
                ui_action_id: null,
                root_path: null,
                path: '/bulk_uploads',
                visibility: true,
                attributes: null,
                ui_action: null,
                display_order: 153,
            },
        ],
    },
    {
        enableRecordWatcher: true,
        id: 9,
        uuid: '5bce98ab-7444-41b4-aaf5-58649dd7510d',
        product_id: 4,
        name: 'Reports',
        label: 'Reports',
        display_name: 'Reports',
        image: 'ReportMenuSvgIcon',
        description: null,
        root_path: '/report',
        path: '/reports',
        ui_action_id: null,
        spacer_above: true,
        display_order: 200,
        active: true,
        attributes: {},
        ui_action: null,
        menus: [
            {
                enableRecordWatcher: true,
                id: 22,
                uuid: '88139d47-f74e-4e1e-bd57-5f8a3719ec03',
                name: ' Pending Approvals',
                label: 'Pending Approvals',
                display_name: 'Pending Approvals',
                image: null,
                description:
                    'Invoices (Expenses/Reimbursement/Advances) awaiting approval and with a "In Progress" verification status.',
                ui_action_id: null,
                root_path: null,
                path: '/reports/ap-todays-pending-approvals',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: 0,
            },
            {
                enableRecordWatcher: true,
                id: 169,
                uuid: '88139d47-f74e-4e1e-bd57-5f8a3719ec03',
                name: 'Reports List',
                label: 'Reports',
                display_name: 'Reports',
                image: null,
                description: 'Reports',
                ui_action_id: null,
                root_path: null,
                path: '/reports',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: null,
            },
            {
                enableRecordWatcher: true,
                id: 171,
                uuid: '88139d47-f74e-4e1e-bd57-5f8a3719ec03',
                name: 'Advances',
                label: 'Advances',
                display_name: 'Advances',
                image: null,
                description: 'A comprehensive list of all raised advances',
                ui_action_id: null,
                root_path: null,
                path: '/reports/ap-advance-approval',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: null,
            },
            {
                enableRecordWatcher: true,
                id: 170,
                uuid: '88139d47-f74e-4e1e-bd57-5f8a3719ec03',
                name: 'On Hold Documents',
                label: 'On Hold Documents',
                display_name: 'On Hold Documents',
                image: null,
                description:
                    'Invoices (Expenses/Reimbursement/Advances) placed on hold by any approver.',
                ui_action_id: null,
                root_path: null,
                path: '/reports/ap-todays-onhold',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: null,
            },
            {
                enableRecordWatcher: true,
                id: 163,
                uuid: '88139d47-f74e-4e1e-bd57-5f8a3719ec03',
                name: 'Rejected Documents',
                label: 'Rejected Documents',
                display_name: 'Rejected Documents',
                image: null,
                description:
                    'Invoices (Expenses/Reimbursement/Advances) which are rejected at any stage(Verification,FinOps or Payment).',
                ui_action_id: null,
                root_path: null,
                path: '/reports/ap-todays-rejected',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: null,
            },
            {
                enableRecordWatcher: true,
                id: 164,
                uuid: '88139d47-f74e-4e1e-bd57-5f8a3719ec03',
                name: 'Expenses',
                label: 'Expenses',
                display_name: 'Expenses',
                image: null,
                description: 'List of all raised expenses',
                ui_action_id: null,
                root_path: null,
                path: '/reports/ap-expense-approval',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: null,
            },
            {
                enableRecordWatcher: true,
                id: 165,
                uuid: '88139d47-f74e-4e1e-bd57-5f8a3719ec03',
                name: ' Pending Payment',
                label: ' Pending Payment',
                display_name: 'Pending Payment',
                image: null,
                description:
                    'Aging of invoices, indicating the overdue invoices in terms of weeks.',
                ui_action_id: null,
                root_path: null,
                path: '/reports/ap-pending-payment',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: null,
            },
            {
                enableRecordWatcher: true,
                id: 162,
                uuid: '88139d47-f74e-4e1e-bd57-5f8a3719ec03',
                name: 'Approved Documents',
                label: 'Approved Documents',
                display_name: 'Approved Documents',
                image: null,
                description:
                    'Invoices (Expenses/Reimbursement/Advances) with approved verification, finops, and payment stages.',
                ui_action_id: null,
                root_path: null,
                path: '/reports/ap-todays-approved',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: null,
            },
            {
                enableRecordWatcher: true,
                id: 166,
                uuid: '88139d47-f74e-4e1e-bd57-5f8a3719ec03',
                name: 'Pending Approvals Aging',
                label: 'Pending Approvals Aging',
                display_name: 'Pending Approvals Aging',
                image: null,
                description:
                    'Ageing of the invoices (Expenses/Reimbursement/Advances) in the submitted state awaiting approval.',
                ui_action_id: null,
                root_path: null,
                path: '/reports/ap-pending-approval-aging',
                visibility: false,
                attributes: null,
                ui_action: null,
                display_order: null,
            },
        ],
    },
    {
        enableRecordWatcher: true,
        id: 18,
        uuid: 'bc6fa87d-3d1a-40cb-90c9-95ec71589201',
        product_id: 4,
        name: 'Logout',
        label: 'Finops Logout',
        display_name: 'Logout',
        image: 'LogoutSvgIcon',
        description: null,
        root_path: null,
        path: null,
        ui_action_id: 88,
        spacer_above: false,
        display_order: 500,
        active: true,
        attributes: '{isBottomMenu:true}',
        ui_action: {
            id: 88,
            uuid: 'e924c225-900c-444b-90ae-ac6d9f17c217',
            created_by: 1,
            updated_by: 1,
            deleted_at: null,
            updated_at: '2023-05-22T05:35:44.774Z',
            created_at: '2023-05-22T05:35:44.774Z',
            name: 'logout',
            label: 'Logout',
            display_name: 'Logout',
            image: null,
            description: null,
            action_id: null,
            validation_id: null,
            attributes: null,
        },
    },
];

export class MenucardHelper extends PageHelper {
    public async init() {
        await this.navigateTo('DASHBOARD');
    }

    public async openAndCloseMenuCard() {
        await this._page
            .locator(`//div[contains(@class,'hamburger_button')]`)
            .click();
    }

    public async getSideBarItems() {
        await this.openAndCloseMenuCard();
        const itemsText = await this._page
            .locator(`//div[contains(@class,'sidebar-items')]`)
            .innerText();

        const itemsArray = itemsText.split('\n');

        const filteredItems = itemsArray.filter((item) => item.trim() !== '');

        const excludedItems = [
            'grid_view',
            'arrow_drop_down',
            'NT',
            'New Test Auto',
            'newtestauto@company.com',
            'arrow_right',
        ];

        const filteredAndCleanedItems = filteredItems.filter((item) => {
            return !excludedItems.includes(item);
        });
        expect(filteredAndCleanedItems).toEqual(mainMenuArray);
    }
    public async checkMenu(menu) {
        const locator = await this.locate(
            "//div[@class='sidebar-block expanded']"
        );
    }
    public async clickOnSideBarMenu(menuName: string) {
        await this._page.waitForTimeout(1000);
        await this._page
            .locator(`//div[contains(@class,'sidebar-items')]`)
            .getByText(menuName, { exact: true })
            .click();
    }

    public async getSidebarSubMenu(menuName: string) {}
}
